global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
scrape_configs:
- job_name: 'app'
  scheme: http
  static_configs:
    - targets:
      - app:8080
      labels:
        __metrics_path__: /actuator/prometheus
